### ISSUE TITLE
PCU limit checks

### ISSUE THREAD

**Issue by BookBurner** [BobDaRoss/QuantumHangarIssues#35]
PCU limit checks against the limits of a player who loads the stuff from hangar, not against the owners of the stuff on the grid.

When a ship is built that is owned by several players, it might lead to inability to load it from the hangar, because it is larger than any single personal PCU limit.

**Comment by BobDaRoss** [comment]
Alright.

Went ahead and added this. However old grids will have to be loaded and saved again for the data to be saved. By default, old grids will still put everything on that one player to keep things backward compatible.

One thing to note, if you change the PCU of a gun while a grid is in the hanger, it won't be updated until you resave it to the hangar. Basically, since I have to save the PCU with the hangar item.
